- name: Install Docker.
  package:
    name: 
      - "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker
  become: yes

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  become: yes

- meta: flush_handlers