---
- name: Ensure old versions of OpenVPN are not installed.
  package:
    name:
      - openpvn
      - easy-rsa
    state: absent
  become: yes

- name: Ensure dependencies are installed.
  yum:
    name:
      - openpvn
      - easy-rsa
      - net-tools
      - openssl
      - bridge-utils
      - openvpn-auth-ldap
    state: present
  become: yes


